import uuid
from datetime import datetime
from sqlalchemy import Column, String, DateTime, ForeignKey, Text, Integer
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship

from app.db.session import Base


class DataSource(Base):
    """Represents a third-party data integration (e.g., Stripe, HubSpot)."""
    __tablename__ = "data_sources"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    organization_id = Column(UUID(as_uuid=True), ForeignKey('organizations.id'), nullable=False)
    name = Column(String(255), nullable=False)
    type = Column(String(50), nullable=False)  # stripe, hubspot, ga4, quickbooks, etc.
    credentials = Column(JSONB, nullable=True)  # Encrypted credentials
    config = Column(JSONB, nullable=True)  # Additional configuration
    status = Column(String(50), nullable=False, default='pending')  # pending, connected, error
    last_sync_at = Column(DateTime, nullable=True)
    sync_error = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    organization = relationship("Organization", back_populates="data_sources")


class Dashboard(Base):
    """Represents a user-created dashboard."""
    __tablename__ = "dashboards"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    organization_id = Column(UUID(as_uuid=True), ForeignKey('organizations.id'), nullable=False)
    name = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    layout = Column(JSONB, nullable=True)  # Grid layout configuration
    is_default = Column(Integer, default=0)  # 1 if this is the default dashboard
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    organization = relationship("Organization", back_populates="dashboards")
    widgets = relationship("Widget", back_populates="dashboard", cascade="all, delete-orphan")


class Widget(Base):
    """Represents a single widget on a dashboard (chart, KPI, etc.)."""
    __tablename__ = "widgets"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    dashboard_id = Column(UUID(as_uuid=True), ForeignKey('dashboards.id'), nullable=False)
    name = Column(String(255), nullable=False)
    type = Column(String(50), nullable=False)  # line_chart, bar_chart, kpi, table, etc.
    data_source_id = Column(UUID(as_uuid=True), ForeignKey('data_sources.id'), nullable=True)
    query = Column(JSONB, nullable=False)  # Query configuration
    position = Column(JSONB, nullable=True)  # Position on the grid
    config = Column(JSONB, nullable=True)  # Widget-specific configuration
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    dashboard = relationship("Dashboard", back_populates="widgets")


class Briefing(Base):
    """Stores AI-generated daily briefings."""
    __tablename__ = "briefings"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    organization_id = Column(UUID(as_uuid=True), ForeignKey('organizations.id'), nullable=False)
    date = Column(DateTime, nullable=False)
    content = Column(Text, nullable=False)  # Markdown content
    highlights = Column(JSONB, nullable=True)  # Key highlights
    alerts = Column(JSONB, nullable=True)  # Any alerts or warnings
    created_at = Column(DateTime, default=datetime.utcnow)


class Alert(Base):
    """Stores predictive alerts generated by AI."""
    __tablename__ = "alerts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    organization_id = Column(UUID(as_uuid=True), ForeignKey('organizations.id'), nullable=False)
    type = Column(String(50), nullable=False)  # anomaly, prediction, threshold
    severity = Column(String(20), nullable=False)  # info, warning, critical
    title = Column(String(255), nullable=False)
    message = Column(Text, nullable=False)
    data = Column(JSONB, nullable=True)  # Additional data
    is_read = Column(Integer, default=0)
    is_dismissed = Column(Integer, default=0)
    created_at = Column(DateTime, default=datetime.utcnow)
